<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ael</string>
	</array>
	<key>name</key>
	<string>AEL2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>any-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
			</array>
		</dict>
		<key>arrow</key>
		<dict>
			<key>match</key>
			<string>=&gt;</string>
			<key>name</key>
			<string>comment.line.double-slash.ael</string>
		</dict>
		<key>assignment</key>
		<dict>
			<key>begin</key>
			<string>(\s?)(=)(?!&gt;)( ?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ael</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ael</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=;|\))</string>
			<key>name</key>
			<string>meta.assignment.ael</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#any-string</string>
				</dict>
			</array>
		</dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.curly.ael</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.braces.curly.ael</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ael</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a comment line</string>
			<key>match</key>
			<string>\s*(//).*</string>
			<key>name</key>
			<string>comment.line.double-slash.ael</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Days of week</string>
					<key>match</key>
					<string>\b(mon|tue|wed|thu|fri|sat|sun)\b</string>
					<key>name</key>
					<string>support.constant.ael</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Months</string>
					<key>match</key>
					<string>\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b</string>
					<key>name</key>
					<string>support.constant.ael</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>times</string>
					<key>match</key>
					<string>\d{1,2}:\d\d</string>
					<key>name</key>
					<string>support.constant.ael</string>
				</dict>
			</array>
		</dict>
		<key>context</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.context.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.ael</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>context section</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(context)(\s+default)?(?=\s|$)</string>
			<key>name</key>
			<string>meta.context.ael</string>
		</dict>
		<key>expressions</key>
		<dict>
			<key>begin</key>
			<string>\$\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.shell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.shell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expression.ael</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#any-string</string>
				</dict>
			</array>
		</dict>
		<key>extension</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=^|\s|/)_(\.?)(?!.*=[^&gt;])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.ael</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.deprecated.ael</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>pattern extension</string>
					<key>end</key>
					<string>(?:(/(?!/))|(=&gt;))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.ael</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.ael</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.regexp.ael</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pattern-string-shallow</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.ael</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ael</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.ael</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.ael</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>special or regular extension</string>
					<key>match</key>
					<string>(?x)
  (?:(s|a|o|t|T|i|e|h)|([\w\-\*#\.\!]+))
  (?:\s*(=&gt;)|(/(?!/))(?=.*?=&gt;))</string>
					<key>name</key>
					<string>meta.extension.ael</string>
				</dict>
			</array>
		</dict>
		<key>globals</key>
		<dict>
			<key>comment</key>
			<string>globals section</string>
			<key>match</key>
			<string>(?&lt;=^|\s)(globals)(?=\s|$)</string>
			<key>name</key>
			<string>meta.globals.ael keyword.other.globals.ael</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\-])(includes|e?switches)(?![\w\-])</string>
					<key>name</key>
					<string>keyword.other.ael</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\-])(abstract|regexten|local(?=\s.*?=))(?![\w\-])</string>
					<key>name</key>
					<string>storage.modifier.ael</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\-])(default(?=:)|else|goto|jump|switch|return|break|continue)(?![\w\-])</string>
					<key>name</key>
					<string>keyword.control.ael</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(pattern)(?![\w\-])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>:</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#pattern-string-shallow</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(case)(?![\w\-])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>:</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.ael</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.ael</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>special or regular extension</string>
							<key>match</key>
							<string>(?:(s|a|o|t|T|i|e|h)|([\w\-\*#]+))</string>
							<key>name</key>
							<string>meta.extension.ael</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(catch)(?![\w\-])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\{</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.ael</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.ael</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>special or regular extension</string>
							<key>match</key>
							<string>(?:(s|a|o|t|T|i|e|h)|([\w\-\*#]+))</string>
							<key>name</key>
							<string>meta.extension.ael</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(hint|ifTime)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#any-string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(random)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;![\w\-])(if|for|while)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#any-string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.ael</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w\-]+)(?&lt;!default)\:</string>
		</dict>
		<key>macro</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=^|\s)(macro)\s+([\w\-]+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.macro.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.macro.ael</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>macro declaration</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>meta.function.ael</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.ael</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[_$a-zA-Z\-][$\w]*</string>
							<key>name</key>
							<string>variable.parameter.function.ael</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.parameter.function.ael</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#preprocessor</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>macro-call</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.macro.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ael</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&amp;)([\w\-]*)(?=\()</string>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#globals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#any-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#extension</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\d+(\.\d+)?</string>
			<key>name</key>
			<string>constant.numeric.ael</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>(=~|=(?!=)|!|!=|&lt;=|&gt;=|-|\*|\+|/(?!/)|%|&lt;|&gt;|:|\?|\|(?!\|)|&amp;(?!&amp;))</string>
			<key>name</key>
			<string>keyword.operator.ael</string>
		</dict>
		<key>parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.brace.round.ael</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.braces.round</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-assignment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#any-string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>pattern-string-deep</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.-.</string>
							<key>name</key>
							<string>constant.character.escape.ael</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pattern-string-deep</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[XZN]+</string>
					<key>name</key>
					<string>constant.character.escape.ael</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\.!]</string>
					<key>name</key>
					<string>keyword.control.ael</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9a-zA-MO-WY\*#_\+]</string>
					<key>name</key>
					<string>variable.parameter.ael</string>
				</dict>
			</array>
		</dict>
		<key>pattern-string-shallow</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#preprocessor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\-</string>
					<key>name</key>
					<string>comment.line.double-slash.ael</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pattern-string-deep</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.preprocessor.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.preprocessor.ael</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.ael</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ael</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ael</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ael</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ael</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ael</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ael</string>
				</dict>
			</dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>(?x)
  (\#)(include|exec)
  \s+
  (?: ((&lt;).*?(&gt;)) | ((\").*?(\")) | (.*$\n?) )</string>
			<key>name</key>
			<string>meta.preprocessor.include.ael</string>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.ael</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>meta.delimiter.comma.ael</string>
				</dict>
			</array>
		</dict>
		<key>quoted-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.ael</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.ael</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ael</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-assignment</key>
		<dict>
			<key>begin</key>
			<string>(\s?)(=)(?!&gt;)( ?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ael</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ael</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=;|\))</string>
			<key>name</key>
			<string>meta.assignment.ael</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#any-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>begin</key>
			<string>(\$\{)(_{0,2})([\w\-]*)(?=\(|\}|\$|:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.ael</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.ael</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.bracket.ael</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.ael</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.variable.ael</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.ael</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ael</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)(-?\d+)?</string>
					<key>name</key>
					<string>meta.ael</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ael</string>
	<key>uuid</key>
	<string>2bd55ee1-f7cd-47d3-a749-a0f5652d7f3d</string>
</dict>
</plist>
